import {catalogEntries,productCard} from './presentation.js';
import {products,business} from './content.js';
import {normalize,message} from './quote.js';
const $=s=>document.querySelector(s);let items=[];try{items=normalize(JSON.parse(localStorage.getItem('pordosol-quote')||'[]'));}catch{}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3000);}
function update(){try{localStorage.setItem('pordosol-quote',JSON.stringify(items));}catch{}document.querySelectorAll('[data-count]').forEach(e=>e.textContent=items.length);$('#quote-ready').hidden=true;$('#quote-lines').innerHTML=items.length?items.map(i=>{const p=products.find(p=>p.id===i.id);return `<div class="quote-line"><img src="/assets/official/${p.image}.webp" alt=""><div><strong>${p.label}</strong><p>${p.format}</p><label>Pacotes <input type="number" min="1" max="9999" value="${i.quantity}" data-quantity="${p.id}" aria-label="Pacotes de ${p.label} ${p.format}"></label><button class="text-button" data-remove="${p.id}">Remover</button></div></div>`}).join(''):'<p class="empty">Sua cotação está esperando os primeiros sabores.<br><a class="text-link" href="/produtos/">Escolher produtos →</a></p>';$('#quote-form-wrap').hidden=!items.length;}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){let quantity=add.hasAttribute('data-detail')?Number($('#product-qty').value):1;if(!Number.isInteger(quantity)||quantity<1||quantity>9999){$('#product-qty').reportValidity();return;}const existing=items.find(i=>i.id===add.dataset.add);if(existing)existing.quantity=Math.min(9999,existing.quantity+quantity);else items.push({id:add.dataset.add,quantity});items=normalize(items);update();toast('Produto adicionado à cotação');if(add.hasAttribute('data-detail'))$('#quote-dialog').showModal();}if(e.target.closest('[data-quote]'))$('#quote-dialog').showModal();if(e.target.closest('[data-menu]'))$('#menu-dialog').showModal();const close=e.target.closest('[data-close]');if(close)close.closest('dialog').close();const remove=e.target.closest('[data-remove]');if(remove){items=items.filter(i=>i.id!==remove.dataset.remove);update();}const prep=e.target.closest('[data-prep]');if(prep){document.querySelectorAll('[data-prep]').forEach(b=>{b.classList.toggle('active',b===prep);b.setAttribute('aria-pressed',String(b===prep));});const ps=catalogEntries(products.filter(p=>prep.dataset.prep.split(',').includes(p.category)));$('#prep-results').innerHTML='<div class="product-grid">'+ps.map(productCard).join('')+'</div>';if(!matchMedia('(prefers-reduced-motion: reduce)').matches)$('#prep-results').animate([{opacity:0,transform:'translateY(12px)'},{opacity:1,transform:'translateY(0)'}],{duration:350,easing:'ease-out'});}});
$('#quote-lines').addEventListener('change',e=>{if(e.target.matches('[data-quantity]')){const n=Number(e.target.value);if(!Number.isInteger(n)||n<1||n>9999){e.target.reportValidity();e.target.value=items.find(i=>i.id===e.target.dataset.quantity).quantity;return;}items.find(i=>i.id===e.target.dataset.quantity).quantity=n;update();}});
$('#clear-quote').addEventListener('click',()=>{items=[];update();});
$('#quote-form').addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(!data.name.trim()||!data.city.trim()){toast('Preencha seu nome e cidade.');return;}const msg=message(items,data);$('#quote-message').value=msg;$('#whatsapp-send').href='https://wa.me/'+business.phone+'?text='+encodeURIComponent(msg);$('#quote-ready').hidden=false;$('#quote-ready').scrollIntoView({behavior:'smooth',block:'nearest'});});
$('#copy-quote').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#quote-message').value);toast('Mensagem copiada');}catch{$('#quote-message').focus();$('#quote-message').select();toast('Selecione e copie a mensagem acima.');}});update();
const mega=$('#mega-toggle');mega?.addEventListener('click',()=>{const open=mega.getAttribute('aria-expanded')==='true';mega.setAttribute('aria-expanded',String(!open));$('#mega-menu').hidden=open;});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&mega){mega.setAttribute('aria-expanded','false');$('#mega-menu').hidden=true;}});document.addEventListener('click',e=>{if(mega&&!e.target.closest('#mega-menu,.nav-products')){mega.setAttribute('aria-expanded','false');$('#mega-menu').hidden=true;}});
if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&'IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');observer.unobserve(e.target);}}),{threshold:.08});document.querySelectorAll('.section>h2,.feature-copy,.history-teaser,.editorial-grid').forEach(e=>{e.classList.add('reveal');observer.observe(e);});}
$('#quote-form').addEventListener('input',()=>{$('#quote-ready').hidden=true;});
// Motion accompanies discovery without taking over scrolling or delaying controls.
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
document.querySelectorAll('[data-feature]').forEach(button=>button.addEventListener('click',()=>{const p=products.find(p=>p.id===button.dataset.feature);const photo=$('#feature-product');document.querySelectorAll('[data-feature]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));photo.src='/assets/official/'+p.image+'.webp';photo.alt=p.label+' '+p.format;$('#feature-format').textContent=p.format;$('.feature-measure').textContent=p.format.replace(' cm','');$('#feature-link').href='/produto/'+p.id+'/';if(!reducedMotion.matches)photo.animate([{opacity:0,transform:'translateY(18px) rotate(-3deg)'},{opacity:1,transform:'translateY(0) rotate(0)'}],{duration:500,easing:'cubic-bezier(.2,.7,.2,1)'});}));
const masthead=$('.site-header');let scrollQueued=false;const onScroll=()=>{if(scrollQueued)return;scrollQueued=true;requestAnimationFrame(()=>{masthead.classList.toggle('is-scrolled',scrollY>24);scrollQueued=false;});};window.addEventListener('scroll',onScroll,{passive:true});onScroll();
const heroArt=$('.hero-art');if(heroArt&&matchMedia('(hover:hover) and (pointer:fine)').matches){let pointerFrame;heroArt.addEventListener('pointermove',e=>{if(reducedMotion.matches)return;cancelAnimationFrame(pointerFrame);pointerFrame=requestAnimationFrame(()=>{const r=heroArt.getBoundingClientRect();heroArt.style.setProperty('--pointer-x',((e.clientX-r.left)/r.width-.5)*12+'px');heroArt.style.setProperty('--pointer-y',((e.clientY-r.top)/r.height-.5)*10+'px');});});heroArt.addEventListener('pointerleave',()=>{cancelAnimationFrame(pointerFrame);heroArt.style.setProperty('--pointer-x','0px');heroArt.style.setProperty('--pointer-y','0px');});}
document.querySelector('[data-print]')?.addEventListener('click',()=>window.print());
document.querySelector('[data-share]')?.addEventListener('click',async()=>{const url=document.querySelector('link[rel=canonical]').href;try{if(navigator.share){await navigator.share({title:document.title,url});return;}}catch(e){if(e.name==='AbortError')return;}try{await navigator.clipboard.writeText(url);toast('Link do produto copiado');}catch{toast('Copie o endereço desta página para compartilhar.');}});
document.querySelectorAll('[data-category]').forEach(link=>link.addEventListener('click',e=>{if(!$('#catalog-results')||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();document.querySelectorAll('[data-category]').forEach(a=>{a.classList.toggle('active',a===link);if(a===link)a.setAttribute('aria-current','true');else a.removeAttribute('aria-current');});const ps=catalogEntries(products.filter(p=>link.dataset.category==='all'||p.category===link.dataset.category));$('#catalog-results').innerHTML='<div class="product-grid">'+ps.map(productCard).join('')+'</div>';$('#catalog-status').textContent=ps.length+' opções encontradas.';}));
document.querySelectorAll('[data-business]').forEach(button=>button.addEventListener('click',()=>{const type=button.dataset.business;document.querySelectorAll('[data-business]').forEach(b=>{b.setAttribute('aria-pressed',String(b===button));b.classList.toggle('active',b===button);});const ids=type==='Pastelaria'?['massas','discos','canudinhos']:type==='Lanchonete'?['massas','pizzas','paes','canudinhos']:['massas','discos','pizzas','paes','canudinhos'];$('#business-intro').textContent='Produtos para começar sua escolha. Consulte o comercial para adequar a compra ao seu negócio.';$('#business-results').innerHTML='<div class="product-grid">'+catalogEntries(products.filter(p=>ids.includes(p.category))).map(productCard).join('')+'</div>';$('#business-whatsapp').href='https://wa.me/'+business.phone+'?text='+encodeURIComponent('Olá! Compro para '+type.toLowerCase()+' e gostaria de conhecer os produtos e as condições de compra da Pôr do Sol.');}));
if(location.hash==='#cotacao')$('#quote-dialog').showModal();
