import {products,business} from './content.js';
import {normalize,message} from './quote.js';
const $=s=>document.querySelector(s);let items=[];try{items=normalize(JSON.parse(localStorage.getItem('pordosol-quote')||'[]'));}catch{}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3000);}
function update(){try{localStorage.setItem('pordosol-quote',JSON.stringify(items));}catch{}document.querySelectorAll('[data-count]').forEach(e=>e.textContent=items.length);$('#quote-ready').hidden=true;$('#quote-lines').innerHTML=items.length?items.map(i=>{const p=products.find(p=>p.id===i.id);return `<div class="quote-line"><img src="/assets/official/${p.image}.webp" alt=""><div><strong>${p.label}</strong><p>${p.format}</p><label>Pacotes <input type="number" min="1" max="9999" value="${i.quantity}" data-quantity="${p.id}" aria-label="Pacotes de ${p.label} ${p.format}"></label><button class="text-button" data-remove="${p.id}">Remover</button></div></div>`}).join(''):'<p class="empty">Sua cotação está esperando os primeiros sabores.<br><a class="text-link" href="/produtos/">Escolher produtos →</a></p>';$('#quote-form-wrap').hidden=!items.length;}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){let quantity=add.hasAttribute('data-detail')?Number($('#product-qty').value):1;if(!Number.isInteger(quantity)||quantity<1||quantity>9999){$('#product-qty').reportValidity();return;}const existing=items.find(i=>i.id===add.dataset.add);if(existing)existing.quantity=Math.min(9999,existing.quantity+quantity);else items.push({id:add.dataset.add,quantity});items=normalize(items);update();toast('Produto adicionado à cotação');if(add.hasAttribute('data-detail'))$('#quote-dialog').showModal();}if(e.target.closest('[data-quote]'))$('#quote-dialog').showModal();if(e.target.closest('[data-menu]'))$('#menu-dialog').showModal();const close=e.target.closest('[data-close]');if(close)close.closest('dialog').close();const remove=e.target.closest('[data-remove]');if(remove){items=items.filter(i=>i.id!==remove.dataset.remove);update();}const prep=e.target.closest('[data-prep]');if(prep){document.querySelectorAll('[data-prep]').forEach(b=>{b.classList.toggle('active',b===prep);b.setAttribute('aria-pressed',String(b===prep));});const ps=products.filter(p=>prep.dataset.prep.split(',').includes(p.category));$('#prep-results').innerHTML='<div class="product-grid">'+ps.map(p=>`<article class="product"><a href="/produto/${p.id}/"><div class="product-picture"><img src="/assets/official/${p.image}.webp" alt="${p.name}"></div><span class="eyebrow">${p.format}</span><h3>${p.label}</h3></a><button class="text-button" data-add="${p.id}">Adicionar à cotação ＋</button></article>`).join('')+'</div>';}});
$('#quote-lines').addEventListener('change',e=>{if(e.target.matches('[data-quantity]')){const n=Number(e.target.value);if(!Number.isInteger(n)||n<1||n>9999){e.target.reportValidity();e.target.value=items.find(i=>i.id===e.target.dataset.quantity).quantity;return;}items.find(i=>i.id===e.target.dataset.quantity).quantity=n;update();}});
$('#clear-quote').addEventListener('click',()=>{items=[];update();});
$('#quote-form').addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(!data.name.trim()||!data.city.trim()){toast('Preencha seu nome e cidade.');return;}const msg=message(items,data);$('#quote-message').value=msg;$('#whatsapp-send').href='https://wa.me/'+business.phone+'?text='+encodeURIComponent(msg);$('#quote-ready').hidden=false;$('#quote-ready').scrollIntoView({behavior:'smooth',block:'nearest'});});
$('#copy-quote').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#quote-message').value);toast('Mensagem copiada');}catch{$('#quote-message').focus();$('#quote-message').select();toast('Selecione e copie a mensagem acima.');}});update();
const mega=$('#mega-toggle');mega?.addEventListener('click',()=>{const open=mega.getAttribute('aria-expanded')==='true';mega.setAttribute('aria-expanded',String(!open));$('#mega-menu').hidden=open;});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&mega){mega.setAttribute('aria-expanded','false');$('#mega-menu').hidden=true;}});document.addEventListener('click',e=>{if(mega&&!e.target.closest('#mega-menu,.nav-products')){mega.setAttribute('aria-expanded','false');$('#mega-menu').hidden=true;}});
if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&'IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');observer.unobserve(e.target);}}),{threshold:.08});document.querySelectorAll('.section>h2,.feature-copy,.history-teaser,.editorial-grid').forEach(e=>{e.classList.add('reveal');observer.observe(e);});}
$('#quote-form').addEventListener('input',()=>{$('#quote-ready').hidden=true;});
