export const business={name:'Pôr do Sol Alimentos',phone:'5588999005560',phoneLabel:'(88) 99900-5560',secondaryPhone:'5588992712966',secondaryLabel:'(88) 99271-2966',landline:'558834234432',email:'pordosolalimentos@hotmail.com',address:'Rua Augusto Fidélis, 2443',city:'Limoeiro do Norte — Ceará',since:'1995'};
export const categories=[{id:'massas',name:'Massas para pastel',short:'Pastel',image:'massa-15x30',description:'O começo de um pastel bem-feito. Escolha o formato para o seu preparo.'},{id:'discos',name:'Discos',short:'Discos',image:'discos-15',description:'Redondinhos, prontos para receber o seu recheio.'},{id:'pizzas',name:'Pizzas',short:'Pizza',image:'mini-pizzas',description:'Mini e micro pizzas para o lanche, a reunião e a festa.'},{id:'paes',name:'Pães árabes',short:'Pães',image:'pao-arabe',description:'Uma base prática para montar beirutes e sanduíches do seu jeito.'},{id:'canudinhos',name:'Canudinhos',short:'Salgados',image:'canudinhos',description:'Prontos para rechear. A criatividade fica por sua conta.'}];
const massaBadges=['Não contém ovos','Não contém lactose','Não contém proteína animal'];
export const products=[
{id:'massa-26x32',name:'Massa para pastel, canudinho e lasanha',label:'Massa para pastel',format:'26 × 32 cm',category:'massas',image:'massa-26x32',page:3,description:'Para quem busca praticidade no preparo de lanches e salgados. Uma massa de fácil manuseio e crocância elevada.',badges:massaBadges,uses:['Pastéis','Canudinhos','Lasanhas'],unit:'pacote'},
{id:'massa-15x30',name:'Massa para pastel, canudinho e lasanha',label:'Massa para pastel',format:'15 × 30 cm',category:'massas',image:'massa-15x30',page:4,description:'Fácil de manusear, com crocância elevada. Um formato versátil para os lanches e salgados da sua cozinha.',badges:massaBadges,uses:['Pastéis','Canudinhos','Lasanhas'],unit:'pacote'},
{id:'discos-15',name:'Discos de massa para pastel',label:'Discos de massa',format:'15 cm · 500 g',category:'discos',image:'discos-15',page:5,description:'Massa redonda da linha Preciosa, apresentada no catálogo Pôr do Sol. Praticidade para rechear e fechar os seus pastéis.',badges:[],uses:['Pastéis'],unit:'pacote'},
{id:'discos-10',name:'Discos de massa para pastel',label:'Discos de massa',format:'10 cm · 200 g',category:'discos',image:'discos-15',page:5,description:'O formato menor dos discos da linha Preciosa. Fácil manuseio para preparar porções e pequenos pastéis.',badges:[],uses:['Pastéis'],unit:'pacote'},
{id:'mini-pizzas',name:'Mini pizzas',label:'Mini pizzas',format:'5 unidades',category:'pizzas',image:'mini-pizzas',page:7,description:'Praticidade para o lanche do dia. Mini pizzas de fácil manuseio, em pacote com cinco unidades.',badges:['Não contém ovos'],uses:['Lanches','Reuniões'],unit:'pacote'},
{id:'micro-pizzas',name:'Micro pizzas',label:'Micro pizzas',format:'24 unidades',category:'pizzas',image:'micro-pizzas',page:6,description:'Para servir em pequenas porções. Cada pacote contém 24 unidades de micro pizzas.',badges:['Não contém ovos'],uses:['Festas','Lanches'],unit:'pacote'},
{id:'pao-arabe',name:'Pães árabes',label:'Pão árabe',format:'5 unidades',category:'paes',image:'pao-arabe',page:8,description:'Uma base para combinar recheios e montar seus lanches. Cada pacote contém cinco unidades.',badges:['Não contém proteína animal'],uses:['Beirutes','Sanduíches'],unit:'pacote'},
{id:'canudinhos',name:'Canudinhos para rechear',label:'Canudinhos',format:'50 unidades',category:'canudinhos',image:'canudinhos',page:9,description:'Praticidade para servir recheios doces ou salgados. Cada pacote contém 50 canudinhos.',badges:massaBadges,uses:['Recheios doces','Recheios salgados'],unit:'pacote'}];
export const preparations=[{id:'pastel',name:'Pastel',categories:['massas','discos'],title:'Um bom pastel começa pela massa.',description:'Escolha entre folhas e discos. O recheio e o seu toque completam a receita.',image:'massa-15x30'},{id:'pizza',name:'Pizza',categories:['pizzas'],title:'Sempre cabe mais um pedaço.',description:'Mini ou micro: encontre a apresentação que combina com o seu lanche.',image:'mini-pizzas'},{id:'paes',name:'Pães',categories:['paes'],title:'Abra espaço para o seu recheio.',description:'Pão árabe, boas combinações e um lanche feito do seu jeito.',image:'pao-arabe'},{id:'salgados',name:'Salgados',categories:['canudinhos','massas'],title:'Pequenos preparos. Muitas ideias.',description:'Massas e canudinhos para dar forma aos seus recheios favoritos.',image:'canudinhos'}];
export const articles=[{id:'escolher-a-massa',title:'Folhas ou discos? Escolha seu formato.',category:'NA HORA DE ESCOLHER',image:'massa-15x30',related:['massa-26x32','massa-15x30','discos-15','discos-10'],intro:'O formato da massa ajuda a organizar o preparo. Conheça as apresentações do catálogo e escolha conforme o lanche que você quer montar.',sections:[['Massas retangulares','As apresentações 26 × 32 cm e 15 × 30 cm são indicadas no catálogo para pastel, canudinho e lasanha. Compare as medidas com o tamanho do seu preparo antes de escolher.'],['Discos redondos','Os discos da linha Preciosa aparecem em 15 cm / 500 g e 10 cm / 200 g. São uma opção para quem prefere começar por uma massa já redonda.'],['Vai comprar para o seu negócio?','Inclua os formatos que interessam na cotação e conte à equipe o que você prepara. O atendimento pode orientar sobre apresentações disponíveis e condições de compra.']]},
{id:'ideias-para-canudinhos',title:'Canudinhos: um recheio para cada ocasião.',category:'PARA INSPIRAR',image:'canudos-prontos',related:['canudinhos'],intro:'Do salgado ao doce, canudinhos convidam a experimentar combinações. Aqui vão ideias para você adaptar à sua cozinha.',sections:[['Para servir salgado','Patês e recheios cremosos bem estruturados são possibilidades de montagem. Escolha uma consistência que permaneça dentro do canudinho e facilite servir.'],['Para uma mesa doce','Doce de leite e cremes de confeitaria podem inspirar versões doces. Teste uma pequena porção para ajustar quantidade, textura e apresentação antes de preparar a mesa toda.'],['Monte perto de servir','A umidade do recheio pode mudar a textura da massa. Organize os componentes separados e faça a montagem perto de servir. Siga as orientações de conservação de cada ingrediente.']]},
{id:'cuidados-com-a-massa',title:'Da embalagem ao preparo: pequenos cuidados.',category:'NO DIA A DIA',image:'pastel',related:['massa-26x32','massa-15x30'],intro:'Uma rotina organizada começa antes do recheio. Reserve um momento para conferir a embalagem e preparar a bancada.',sections:[['Confira a embalagem','Observe integridade, validade e instruções do rótulo. A conservação pode variar de um produto para outro; siga a orientação da apresentação que você comprou.'],['Separe o que vai usar','Deixe utensílios e recheios organizados antes de começar. Retire a quantidade necessária para o preparo e mantenha o restante nas condições indicadas na embalagem.'],['Teste antes de preparar em quantidade','Faça uma pequena porção para ajustar o fechamento e o preparo à sua receita e aos seus equipamentos. Para orientações específicas sobre a massa, fale com a equipe Pôr do Sol.']]}];
