import {business,products,articles,categories} from './content.js';
export const siteOrigin=(process.env.SITE_URL||'https://pordosol.pages.dev').replace(/\/$/,'');
if(!/^https:\/\/[^/]+$/.test(siteOrigin))throw new Error('SITE_URL deve ser uma origem HTTPS, sem caminho.');
export const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function metadata(route,title){
 const product=products.find(p=>route===`/produto/${p.id}/`),article=articles.find(a=>route===`/da-cozinha/${a.id}/`),category=categories.find(c=>route===`/produtos/${c.id}/`);
 const descriptions={'/':'Massas para pastel, pizzas, pães árabes e canudinhos de Limoeiro do Norte, Ceará. Conheça a Pôr do Sol Alimentos e peça sua cotação.','/produtos/':'Explore as massas, discos, pizzas, pães árabes e canudinhos Pôr do Sol. Compare formatos e monte uma cotação pelo WhatsApp.','/nossa-historia/':'Conheça a história da Pôr do Sol Alimentos, de Limoeiro do Norte, no Vale do Jaguaribe. Mais de 30 anos produzindo massas no Ceará.','/contato/':'Fale com a Pôr do Sol Alimentos em Limoeiro do Norte, Ceará. WhatsApp, telefone, e-mail e rota para o endereço da fábrica.','/da-cozinha/':'Dicas para escolher massas, organizar o preparo e combinar recheios. Ideias da cozinha Pôr do Sol para a sua rotina.','/para-seu-negocio/':'Compra para mercado, mercearia, pastelaria, lanchonete ou distribuição? Conheça a linha Pôr do Sol e consulte condições com o comercial.','/privacidade/':'Entenda como funciona a cotação local, o uso do WhatsApp e a privacidade no site Pôr do Sol Alimentos.'};
 const description=product?`${product.label} ${product.format}. ${product.description}`:article?.intro||category?.description||descriptions[route]||title;
 const concise=description.length>165?description.slice(0,162).replace(/\s\S*$/,'')+'…':description;
 const canonical=siteOrigin+route;
 const image=siteOrigin+'/assets/official/'+(product?.image||article?.image||'logo')+'.webp';
 const organization={'@type':'Organization','@id':siteOrigin+'/#organization',name:business.name,url:siteOrigin+'/',logo:siteOrigin+'/assets/official/logo.webp',foundingDate:'1995',telephone:'+'+business.phone,email:business.email,address:{'@type':'PostalAddress',streetAddress:business.address,addressLocality:'Limoeiro do Norte',addressRegion:'CE',addressCountry:'BR'},contactPoint:{'@type':'ContactPoint',telephone:'+'+business.phone,contactType:'vendas',availableLanguage:'pt-BR'}};
 const graph=[organization,{'@type':'WebSite','@id':siteOrigin+'/#website',url:siteOrigin+'/',name:business.name,inLanguage:'pt-BR',publisher:{'@id':organization['@id']}}];
 if(route!=='/')graph.push({'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Início',item:siteOrigin+'/'},...(product?[{'@type':'ListItem',position:2,name:'Produtos',item:siteOrigin+'/produtos/'},{'@type':'ListItem',position:3,name:title,item:canonical}]:[{'@type':'ListItem',position:2,name:title,item:canonical}])]});
 if(product)graph.push({'@type':'Product','@id':canonical+'#produto',url:canonical,name:product.label+' '+product.format,description:product.description,image,brand:{'@type':'Brand',name:product.category==='discos'?'Preciosa':'Pôr do Sol Alimentos'},category:categories.find(c=>c.id===product.category).name});
 const tag=(name,value,property=false)=>`<meta ${property?'property':'name'}="${name}" content="${escapeHtml(value)}">`;
 return `<title>${escapeHtml(title)} | Pôr do Sol Alimentos</title>${tag('description',concise)}<link rel="canonical" href="${canonical}">${route==='/404/'?tag('robots','noindex,follow'):''}${tag('og:type',article?'article':'website',true)}${tag('og:locale','pt_BR',true)}${tag('og:site_name',business.name,true)}${tag('og:title',title+' | Pôr do Sol Alimentos',true)}${tag('og:description',concise,true)}${tag('og:url',canonical,true)}${tag('og:image',image,true)}${tag('og:image:alt',product?product.label+' — fotografia do catálogo oficial':business.name,true)}${tag('twitter:card','summary_large_image')}${tag('twitter:title',title)}${tag('twitter:description',concise)}${tag('twitter:image',image)}${process.env.GOOGLE_SITE_VERIFICATION?tag('google-site-verification',process.env.GOOGLE_SITE_VERIFICATION):''}<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':graph}).replaceAll('<','\\u003c')}</script>`;
}
